### ISSUE TITLE
This error happend

### ISSUE THREAD

**Issue by Fasani** [Fasani/SpottyBot#1]
Trying to play a music track not allowed in given country, or if advert plays.

Now playing: spotify:track:7okrsZ0bOSZM4J0YLmWtUC
crash: TypeError: Cannot read property 'uri' of undefined
    at getTrack (C:\Users\Michael\Documents\GitHub\SpottyBot\app.js:80:32)
    at null._onTimeout (C:\Users\Michael\Documents\GitHub\SpottyBot\app.js:104:2
4)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by Fasani** [comment]
This was when the last track was selected the array count was wrong.
